CREATE TABLE IF NOT EXISTS `tiservicos`.`USER_CONSOLE` (
  `USER_CONSOLE_ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'The User id.',
  `EMAIL` VARCHAR(100) NOT NULL COMMENT 'The user email, used during login.',
  `PWD` VARCHAR(130) NOT NULL COMMENT 'The user pwd, used during login.',
  `STATUS` TINYINT(1) NOT NULL COMMENT 'The user status (0=inactive and 1=active.',
  PRIMARY KEY (`USER_CONSOLE_ID`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tiservicos`.`PROFILE` (
  `PROFILE_ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'The profile id.',
  `NAME` VARCHAR(100) NULL COMMENT 'The profile name.',
  PRIMARY KEY (`PROFILE_ID`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tiservicos`.`USER_CONSOLE_PROFILE` (
  `PROFILE_ID` INT(11) NOT NULL COMMENT 'The profile id.',
  `USER_CONSOLE_ID` INT(11) NOT NULL COMMENT 'The user id.',
  INDEX `fk_USER_PROFILE_PROFILE1_idx` (`PROFILE_ID` ASC),
  INDEX `fk_USER_PROFILE_USER1_idx` (`USER_CONSOLE_ID` ASC),
  CONSTRAINT `fk_USER_PROFILE_PROFILE1`
    FOREIGN KEY (`PROFILE_ID`)
    REFERENCES `tiservicos`.`PROFILE` (`PROFILE_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_PROFILE_USER1`
    FOREIGN KEY (`USER_CONSOLE_ID`)
    REFERENCES `tiservicos`.`USER_CONSOLE` (`USER_CONSOLE_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tiservicos`.`ROLE` (
  `ROLE_ID` INT(11) NOT NULL AUTO_INCREMENT COMMENT 'The role id.',
  `NAME` VARCHAR(100) NOT NULL COMMENT 'The role name.',
  PRIMARY KEY (`ROLE_ID`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tiservicos`.`PROFILE_ROLE` (
  `ROLE_ID` INT(11) NOT NULL COMMENT 'The role id.',
  `PROFILE_ID` INT(11) NOT NULL COMMENT 'The profile id.',
  INDEX `fk_PROFILE_ROLE_ROLE1_idx` (`ROLE_ID` ASC),
  INDEX `fk_PROFILE_ROLE_PROFILE1_idx` (`PROFILE_ID` ASC),
  CONSTRAINT `fk_PROFILE_ROLE_ROLE1`
    FOREIGN KEY (`ROLE_ID`)
    REFERENCES `tiservicos`.`ROLE` (`ROLE_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROFILE_ROLE_PROFILE1`
    FOREIGN KEY (`PROFILE_ID`)
    REFERENCES `tiservicos`.`PROFILE` (`PROFILE_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tiservicos`.`QUESTION_CATEGORY` (
  `QUESTION_CATEGORY_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `QUESTION_CATEGORY_FATHER_ID` BIGINT NULL,
  `NAME` VARCHAR(200) NOT NULL,
  `STATUS` TINYINT(1) NOT NULL,
  PRIMARY KEY (`QUESTION_CATEGORY_ID`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tiservicos`.`QUESTION` (
  `QUESTION_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `QUESTION_CATEGORY_ID` BIGINT NOT NULL,
  `USER_CONSOLE_ID` INT(11) NOT NULL,
  `QUESTION` VARCHAR(200) NOT NULL,
  `ANSWER_ID` BIGINT NOT NULL,
  PRIMARY KEY (`QUESTION_ID`),
  INDEX `fk_QUESTION_QUESTION_CATEGORY1_idx` (`QUESTION_CATEGORY_ID` ASC),
  INDEX `fk_QUESTION_USER_CONSOLE1_idx` (`USER_CONSOLE_ID` ASC),
  INDEX `fk_QUESTION_ANSWER1_idx` (`ANSWER_ID` ASC),
  CONSTRAINT `fk_QUESTION_QUESTION_CATEGORY1`
    FOREIGN KEY (`QUESTION_CATEGORY_ID`)
    REFERENCES `tiservicos`.`QUESTION_CATEGORY` (`QUESTION_CATEGORY_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QUESTION_USER_CONSOLE1`
    FOREIGN KEY (`USER_CONSOLE_ID`)
    REFERENCES `tiservicos`.`USER_CONSOLE` (`USER_CONSOLE_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_QUESTION_ANSWER1`
    FOREIGN KEY (`ANSWER_ID`)
    REFERENCES `tiservicos`.`ANSWER` (`ANSWER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tiservicos`.`ANSWER` (
  `ANSWER_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `ANSWER` MEDIUMTEXT NOT NULL,
  `BIBLIOGRAPHY_REFERENCES` TEXT NULL,
  PRIMARY KEY (`ANSWER_ID`))
ENGINE = InnoDB

CREATE TABLE IF NOT EXISTS `tiservicos`.`ATTACHMENT` (
  `ATTACHMENT_ID` BIGINT NOT NULL AUTO_INCREMENT,
  `ANSWER_ID` BIGINT NOT NULL,
  `NAME` VARCHAR(200) NOT NULL,
  `TYPE` VARCHAR(30) NOT NULL,
  `SIZE` VARCHAR(50) NOT NULL,
  `FILE` LONGBLOB NOT NULL,
  PRIMARY KEY (`ATTACHMENT_ID`),
  INDEX `fk_ATTACHMENT_ANSWER1_idx` (`ANSWER_ID` ASC),
  CONSTRAINT `fk_ATTACHMENT_ANSWER1`
    FOREIGN KEY (`ANSWER_ID`)
    REFERENCES `tiservicos`.`ANSWER` (`ANSWER_ID`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
